### ISSUE TITLE
Keys: duplicate key alias occurs

### ISSUE THREAD

**Issue by Leekailklk** [Bytom/bytom#479] opened 2018-03-24 12:37 UTC
Environment

- OS: win7 64

#### Problem Description

when I test make some new keys on dashboard, the duplicate key alias occurs once.

Nothing special,just make new key on dashboard. Suddenly I found same alias keys can made. So I try to made some new accounts and assets, the duplicate info show. Then I try to make same new key the duplicate check works and can not make same alias key. But the first time, I made duplicate key alias successfully.
see the following info
G:\bytom>bytomcli list-keys
0 :
{
  "alias": "likai's key",
  "file": "G:\\bytom\\.bytomd\\keystore\\UTC--2018-03-22T10-48-53.857552300Z--21
13a9a8-be47-4486-8f01-e31a613e6293",
  "xpub": "a6a99d8c5d1f1999b0401aca262f40edb68bdfb2ea456cabaf239c1c300bab401589a
732b680cb2fee0cc823b04ebec0c7ef4aadaf0044e3c9b652ca3ed139b1"
}
1 :
{
  "alias": "afu's key",
  "file": "G:\\bytom\\.bytomd\\keystore\\UTC--2018-03-22T10-49-44.781465000Z--a6
6b9198-0565-457b-ac1d-baf1c4ec74e6",
  "xpub": "e0422330bd14a5ac4770aee5757f6217cfd798bebd9bdb61f451a02dbb9053fcac05f
3dce6a39ce719a3303ffeebd5ef473ac0e3fd1720d4ec65b39e0dde7c6c"
}
2 :
{
  "alias": "zxc",
  "file": "G:\\bytom\\.bytomd\\keystore\\UTC--2018-03-22T11-09-42.601972500Z--89
c7d881-9163-4172-8b6a-d232efeb078d",
  "xpub": "02fc9f91e3b8f54922325023835c6d635a2437026e65de2f553506e86a438d015475f
b9752cefdae46b735a0a9356663c4bd296bf8cdb7c0dd206de11efe6971"
}
3 :
{
  "alias": "test",
  "file": "G:\\bytom\\.bytomd\\keystore\\UTC--2018-03-24T12-07-54.475992700Z--c5
a15b0d-9b4c-4eb4-82ce-92def4d2f3b0",
  "xpub": "facc4f834246e5668a91a2fdd0b9e6d9fcd5f2d447174b748daaee9d2834a60fe4ac3
f1037278eab9ee8334294920fbed100711841642463af7ce78534765226"
}
4 :
{
  "alias": "test",
  "file": "G:\\bytom\\.bytomd\\keystore\\UTC--2018-03-24T12-07-54.475992700Z--f9
c7c254-56bb-4a44-a470-ff610d40d6de",
  "xpub": "ae1d1090fb84ffa275c8116a33e6babba2115265f67ca8d910195d03999a52dd9f339
659e347cb725d6ae82594d7e3a2fd42380573ec4b103bed5c6da8caf0b7"
}

**Comment by Leekailklk** [comment] 2018-03-24 15:03
I didn't full understand the source code. But I feel the func:"func (kc *keyCache) add(newKey XPub)" in bytom\blockchain\pseudohsm\keycache.go looks a little strange. And I noticed the two key file have the same prefix.It looks strange either.

**Comment by wliyongfeng** [comment] 2018-03-26 02:03
@Leekailklk I can't reproduce this bug.

**Comment by Leekailklk** [comment] 2018-03-27 14:56
This problem only happened once(0.4 version). I try to reproduce this bug. My computer is an old one. The two key have the same produce time. So I guess when the first key was create successfully the computer didn't finish the process due to it's slow speed on net or harddisk etc. I try to simulate poor net connection or poor disk write situation. Finally I find the reason maybe is the first key create successfully and ready to write from memory into disk file but delay to write to file. Then the second same alias name key was create and pass the duplicate check. I found another way to reproduce the bug, removed the key file from keystore folder then you can create the same alias name key and copy back the previous one. Then you can have 2 same alias name key. Anyway, if the computer is busy to deal with other problem and delay to write the file from memory into disk, I guess the problem happened.
G:\bytom>bytomcli list-keys
0 :
{
  "alias": "test10",
  "file": "G:\\bytom\\.bytomd\\keystore\\UTC--2018-03-27T13-29-50.352569400Z--e0
f8e296-f24b-4033-808f-c142119cb8a7",
  "xpub": "15cd336bcba338f8835b573946c7d18cc223408950d0bcb9a6719a736d4322f5c9645
8933a070e3e0e6f1895cd997ac1bcb88d05f7f7041153cc42d2469b720a"
}
1 :
{
  "alias": "test10",
  "file": "G:\\bytom\\.bytomd\\keystore\\UTC--2018-03-27T13-32-05.432822600Z--d3
bf83f9-2062-481a-babc-31d07b86d816",
  "xpub": "624569c9178505f4373be0538961fac3cd72952182ee336c41cd10ef5e5e777737ba1
c24b22f7b16cdb770b51a8a59dd1ac6acdfd59c191aaca23d70735b4f02"
}
2 :
{
  "alias": "test11",
  "file": "G:\\bytom\\.bytomd\\keystore\\UTC--2018-03-27T13-34-42.485165500Z--34
a6c88c-bfc0-4add-87ef-27d623768aa3",
  "xpub": "5b2eedf0aeebdca6cdd287a034ed1eadb28fe84fe766199da5059460d45abc5bfdda2
a42498a812a2391f347cd9cb632ae27bbea029d327947dab60aa7646a6b"
}
3 :
{
  "alias": "test11",
  "file": "G:\\bytom\\.bytomd\\keystore\\UTC--2018-03-27T13-36-44.050638400Z--7b
945c9a-307a-40ee-a7b6-ca5dee537ece",
  "xpub": "9dfd6f0df15a97f71de51d8875cdc35deda461a21846c1b0e5948e8e50ae407cab4c9
162e02c24c22d775d5dc9a12de07a77bfb2fc2a1dad4629dd8eefc6423d"
}
4 :
{
  "alias": "test11",
  "file": "G:\\bytom\\.bytomd\\keystore\\UTC--2018-03-27T13-37-20.750766900Z--a8
9e04af-5b12-493f-be1e-8a95f95b3eb0",
  "xpub": "ca53bea51f7c0a1e6049a2487c0e1d9672927c8010383e5781e55cc1efb9a07a04b19
a5c89fc68fbce24e15c364d8f26956e8ef0a48f53db1dbabb071af121ed"
}

**Comment by Leekailklk** [comment] 2018-03-27 23:40
It seems I found the problem. When create or list keys should cause "func (kc *keyCache) reload()" in bytom\blockchain\pseudohsm\keycache.go to reload caches addresses of existing key. But when click the icons "key" in the dashboard. It didn't refresh to cause the "func (kc *keyCache) reload()" to reload  caches addresses of existing key. Then the duplicate check will not get the latest keys list.

**Comment by Leekailklk** [comment] 2018-03-28 00:02
I think there are two problems
1.
When create one key,the key was not finish writing into file in keystore folder. Then create another same alias key will works.
2.
The key button in dashboard didn't refresh to cause  "func (kc *keyCache) reload()" in bytom\blockchain\pseudohsm\keycache.go to reload caches addresses of existing key. That also can
make same alias key if you only remove the old one away from the keystore folder. When you click the key button in the dashboard, What you see is not the exactly what you can get in the keystore.
They are two different questions.

**Comment by Leekailklk** [comment] 2018-03-28 00:47
For the above problem 1. 
I think when create a key should make sure the key was write into files successfully then can make another key. In another words, before create a key should make sure the previous key was made and write into file successfully.

**Comment by wliyongfeng** [comment] 2018-03-28 06:17
@Leekailklk Great work.

**Comment by wliyongfeng** [comment] 2018-03-28 06:20
@Leekailklk Great work.

We solve the 1st problem. While we consider the 2nd case users' operation exception, currently it's not high priority to solve it.

**Comment by wliyongfeng** [comment] 2018-03-28 06:26
@Leekailklk Due to you created #493 , can I close this issue?

**Comment by Leekailklk** [comment] 2018-03-28 12:14
Yes, you can close it. And thanks for your suggestion. I will learn markdown and try to use it on next issue.

**Closed** 2018-03-29 01:24 UTC
